version: '3.8'

services:
  strapi:
    build: .
    container_name: strapi
    restart: unless-stopped
    ports:
      - '1337:1337'
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./config:/app/config
      - ./src:/app/src
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - strapi-network

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    container_name: strapi_db
    environment:
      POSTGRES_DB: strapi_db
      POSTGRES_USER: strapi_user
      POSTGRES_PASSWORD: strapi_pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U strapi_user -d strapi_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - strapi-network

volumes:
  postgres-data:

networks:
  strapi-network:
    driver: bridge
